const PROGRAM = {
  A: {
    title: 'Pass A',
    subtitle: 'Ben, bröst, rygg, armar och bål',
    exercises: [
      {id:'benpress',name:'Benpress',muscle:'Lår och rumpa',muscleLong:'Framsida lår, baksida lår och sätesmuskler',desc:'Huvudsakligen lår och säte. Bålen hjälper till att hålla kroppen stabil.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'legs',setup:['Sitt med hela ryggen mot ryggstödet.','Placera fötterna ungefär axelbrett mitt på plattan.','Knäna ska vara tydligt böjda, men bäckenet ska ligga kvar mot sitsen.'],perform:['Pressa plattan bort från dig genom hela foten.','Sträck benen nästan helt utan att låsa knäna hårt.','Sänk långsamt tillbaka till ett bekvämt djup.'],cue:'Hela foten i plattan. Knäna följer tårna. Ryggen kvar mot stolen.',mistakes:['För tung vikt','Knäna faller inåt','Rumpan lyfter från sitsen','Studsar längst ner']},
      {id:'brostpress',name:'Bröstpress',muscle:'Bröst och triceps',muscleLong:'Bröstmuskler, främre axel och triceps',desc:'Pressövning för överkroppen med stöd från maskinen.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'chest',setup:['Ställ sitsen så att handtagen hamnar ungefär mitt på bröstet.','Ha fötterna stadigt i golvet och ryggen mot stödet.','Dra skulderbladen lätt bakåt och nedåt.'],perform:['Pressa handtagen framåt kontrollerat.','Stanna när armarna nästan är raka.','För handtagen långsamt tillbaka.'],cue:'Bröstet upp. Axlarna ner. Pressa lugnt.',mistakes:['Axlarna åker upp mot öronen','För stor svank','Släpper tillbaka vikten snabbt']},
      {id:'sittande-rodd',name:'Sittande rodd',muscle:'Rygg och biceps',muscleLong:'Övre rygg, lats och biceps',desc:'Dragövning som stärker ryggen och hjälper hållningen.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'back',setup:['Sitt upprätt med lätt böjda knän.','Greppa handtaget med raka armar.','Håll ryggen neutral och bröstet lätt upp.'],perform:['Dra handtaget mot magen.','För skulderbladen bakåt medan armbågarna passerar kroppen.','Släpp fram armarna långsamt igen.'],cue:'Dra med ryggen, inte bara armarna.',mistakes:['Gungar med överkroppen','Rycker i vikten','Drar axlarna uppåt']},
      {id:'goblet-squat',name:'Goblet squat',muscle:'Ben och bål',muscleLong:'Framsida lår, rumpa och bål',desc:'Kontrollerad knäböj som tränar ben och kroppskontroll.',lucas:'2 × 8–12',magnus:'3 × 8–12',highlight:'legs',setup:['Stå ungefär axelbrett med tårna lätt utåt.','Lucas börjar gärna utan vikt eller med en mycket lätt hantel.','Håll vikten nära bröstet.'],perform:['Sätt dig nedåt och lite bakåt.','Låt knäna följa tårnas riktning och håll hela foten i golvet.','Res dig genom att trycka golvet ifrån dig.'],cue:'Bröst upp. Knän mot tår. Hela foten i golvet.',mistakes:['Hälarna lyfter','Knäna faller inåt','Ryggen rundas']},
      {id:'latsdrag',name:'Latsdrag',muscle:'Rygg och armar',muscleLong:'Breda ryggmuskeln, övre rygg och biceps',desc:'Vertikal dragövning för ryggen med stabil sittposition.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'back',setup:['Justera lårstödet så att benen hålls på plats.','Greppa stången något bredare än axelbrett.','Sitt högt med bröstet lätt upp.'],perform:['Dra stången mot övre delen av bröstet.','För armbågarna nedåt mot sidorna.','Släpp långsamt upp tills armarna nästan är raka.'],cue:'Tänk armbågar mot golvet.',mistakes:['Drar stången bakom huvudet','Lutar sig kraftigt bakåt','Använder fart']},
      {id:'planka',name:'Planka',muscle:'Bål',muscleLong:'Mage och djupa bålmuskler',desc:'Statisk bålövning med fokus på en stabil kroppslinje.',lucas:'2 × 15–30 sek',magnus:'3 × 30–60 sek',highlight:'core',setup:['Placera armbågarna under axlarna.','Stöd på underarmar och tår.','Spänn magen och rumpan lätt.'],perform:['Håll kroppen ungefär rak från huvud till hälar.','Andas normalt under hela tiden.','Avsluta när positionen börjar försämras.'],cue:'Spänn magen som om någon ska peta dig i magen.',mistakes:['Höften sjunker','Rumpan hamnar för högt','Håller andan']}
    ]
  },
  B: {
    title:'Pass B',
    subtitle:'Ben, axlar, rygg, rumpa och bål',
    exercises:[
      {id:'larcurl',name:'Lårcurl',muscle:'Baksida lår',muscleLong:'Hamstrings på baksidan av låret',desc:'Isolerar baksida lår med kontrollerad knäböjning.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'legs',setup:['Justera maskinen så att knäleden ligger nära maskinens vridpunkt.','Placera dynan strax ovanför ankeln.','Sitt eller ligg stabilt enligt maskinens utformning.'],perform:['Böj knäna och dra dynan bakåt eller nedåt.','Pausa kort i det böjda läget.','Släpp långsamt tillbaka.'],cue:'Lugnt åt båda hållen.',mistakes:['Lyfter höften','För tung vikt','Kastar tillbaka vikten']},
      {id:'axelpress',name:'Axelpress',muscle:'Axlar och triceps',muscleLong:'Axlar och triceps',desc:'Stabil pressövning för axlar och armar.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'shoulders',setup:['Ställ sitsen så att handtagen börjar ungefär i axelhöjd.','Ha ryggen mot stödet och fötterna i golvet.','Spänn magen lätt.'],perform:['Pressa handtagen uppåt tills armarna nästan är raka.','Behåll ryggen mot stödet.','Sänk långsamt tillbaka.'],cue:'Mage spänd. Axlar ner. Pressa rakt upp.',mistakes:['Stor svank','För tung vikt','Axlarna åker upp']},
      {id:'kabelrodd',name:'Kabelrodd',muscle:'Rygg och armar',muscleLong:'Övre rygg, lats och biceps',desc:'Kontrollerad horisontell dragövning med kabel.',lucas:'2 × 10–15',magnus:'3 × 8–12',highlight:'back',setup:['Sitt stabilt med neutral rygg.','Greppa handtaget och håll armarna raka i startläget.','Ha lätt böjda knän.'],perform:['Dra handtaget mot magen.','Pausa med armbågarna bredvid kroppen.','Släpp långsamt fram igen.'],cue:'Stabil kropp. Dra armbågarna bakåt.',mistakes:['Gungar fram och tillbaka','Rycker i vikten','Tappar hållningen']},
      {id:'step-up',name:'Step-up',muscle:'Ben och balans',muscleLong:'Framsida lår, rumpa och balansmuskulatur',desc:'Enbensövning som utvecklar balans och benstyrka.',lucas:'2 × 8 per ben',magnus:'3 × 8–10 per ben',highlight:'legs',setup:['Använd en låg stepbräda, särskilt för Lucas.','Sätt hela ena foten på brädan.','Stå nära brädan och håll kroppen upprätt.'],perform:['Tryck genom foten på brädan och kliv upp.','Stå upprätt på toppen.','Kliv kontrollerat ned igen.'],cue:'Benet på brädan gör jobbet.',mistakes:['Skjuter ifrån för mycket med foten på golvet','Knä faller inåt','För hög bräda']},
      {id:'hoftlyft',name:'Höftlyft',muscle:'Rumpa',muscleLong:'Sätesmuskler och baksida lår',desc:'Enkel och säker höftövning som passar bra i början.',lucas:'2 × 12–15',magnus:'3 × 10–15',highlight:'glutes',setup:['Ligg på rygg med böjda knän.','Placera fötterna stadigt i golvet.','Spänn magen lätt.'],perform:['Pressa genom fötterna och lyft höften.','Spänn rumpan kort högst upp.','Sänk långsamt tillbaka.'],cue:'Pressa genom fötterna. Spänn rumpan.',mistakes:['Överdriver svanken','Fötterna för långt bort','Tappar kontrollen']},
      {id:'sidoplanka',name:'Sidoplanka',muscle:'Bål',muscleLong:'Sidomage och stabiliserande bålmuskler',desc:'Stabilitetsövning för sidan av bålen.',lucas:'2 × 15–25 sek/sida',magnus:'3 × 25–45 sek/sida',highlight:'core',setup:['Placera armbågen direkt under axeln.','Lucas kan börja med böjda knän.','Håll huvudet i linje med kroppen.'],perform:['Lyft höften från golvet.','Håll kroppen stabil och andas normalt.','Sänk kontrollerat när tiden är slut.'],cue:'Höften upp. Kroppen lång.',mistakes:['Höften sjunker','Axeln kollapsar','Håller andan']}
    ]
  }
};


const GENERATED_IMAGE_IDS=new Set(['benpress','brostpress','sittande-rodd','goblet-squat','latsdrag','planka']);
function exerciseAsset(ex){return `assets/exercises/${ex.id}.${GENERATED_IMAGE_IDS.has(ex.id)?'webp':'svg'}`}

const STORE_KEY='magnus-lucas-gym-v1';
const defaultState={week:1,pass:'A',exerciseIndex:0,logs:{},globalNotes:'',history:{}};
let state=loadState();

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORE_KEY,JSON.stringify(state));refreshProgress()}
function keyFor(pass=state.pass,index=state.exerciseIndex,week=state.week){return `w${week}-${pass}-${PROGRAM[pass].exercises[index].id}`}
function getLog(){const k=keyFor();if(!state.logs[k])state.logs[k]={sets:[{},{},{}],note:'',done:false,updated:null};return state.logs[k]}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

function renderWeekOptions(){const s=$('#weekSelect');s.innerHTML=Array.from({length:8},(_,i)=>`<option value="${i+1}">Vecka ${i+1}</option>`).join('');s.value=state.week}
function renderTabs(){const box=$('#exerciseTabs');box.innerHTML=PROGRAM[state.pass].exercises.map((ex,i)=>{const done=state.logs[`w${state.week}-${state.pass}-${ex.id}`]?.done;return `<button class="exercise-tab ${i===state.exerciseIndex?'active':''} ${done?'done':''}" data-index="${i}" role="tab" aria-selected="${i===state.exerciseIndex}"><img src="${exerciseAsset(ex)}" alt=""><span>${i+1}. ${esc(ex.name)}</span></button>`}).join('');box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.exerciseIndex=Number(b.dataset.index);saveState();renderToday()}))}
function renderList(sel,items){$(sel).innerHTML=items.map(x=>`<li>${esc(x)}</li>`).join('')}
function highlightPath(type){const map={legs:'M58 126 Q90 116 122 126 L136 199 Q90 211 44 199 Z',chest:'M61 62 Q90 48 119 62 L113 111 Q90 120 67 111 Z',back:'M55 57 Q90 43 125 57 L117 120 Q90 134 63 120 Z',shoulders:'M46 55 Q90 42 134 55 L125 78 Q90 68 55 78 Z',core:'M68 82 Q90 74 112 82 L111 130 Q90 139 69 130 Z',glutes:'M67 116 Q90 103 113 116 L117 145 Q90 158 63 145 Z'};$('#bodyHighlight').setAttribute('d',map[type]||map.core)}
function renderToday(){
  const p=PROGRAM[state.pass], ex=p.exercises[state.exerciseIndex], log=getLog();
  $('#passHeading').textContent=`🏋 ${p.title}`;$('#passSubtitle').textContent=p.subtitle;
  $$('[data-pass]').forEach(b=>b.classList.toggle('active',b.dataset.pass===state.pass));
  $('#exerciseNumber').textContent=`Övning ${state.exerciseIndex+1}`;$('#exerciseName').textContent=ex.name;$('#exerciseMuscle').textContent=ex.muscle;$('#muscleName').textContent=ex.muscleLong;$('#muscleDescription').textContent=ex.desc;$('#exerciseImage').src=exerciseAsset(ex);$('#exerciseImage').alt=`Illustration av ${ex.name}`;
  $('#lucasPrescription').textContent=ex.lucas;$('#magnusPrescription').textContent=ex.magnus;renderList('#setupList',ex.setup);renderList('#performList',ex.perform);$('#cueText').textContent=ex.cue;renderList('#mistakeList',ex.mistakes);highlightPath(ex.highlight);
  renderTabs();renderSetRows();$('#exerciseNotes').value=log.note||'';$('#completeExercise').classList.toggle('done',!!log.done);$('#completeExercise').textContent=log.done?'✓ Övningen är klar':'✓ Markera övning som klar';
  $('#exerciseCounter').textContent=`${state.exerciseIndex+1} av ${p.exercises.length}`;$('#prevExercise').disabled=state.exerciseIndex===0;$('#nextExercise').textContent=state.exerciseIndex===p.exercises.length-1?'Till första övningen →':'Nästa övning →';
}
function renderSetRows(){const log=getLog();const lucasTwoSets=true;$('#setRows').innerHTML=[0,1,2].map(i=>{const r=log.sets[i]||{};const dis=i===2&&lucasTwoSets?'disabled':'';return `<tr><td><strong>${i+1}</strong></td><td><input ${dis} inputmode="decimal" type="number" min="0" max="500" step="0.5" data-set="${i}" data-key="lw" value="${esc(r.lw)}"></td><td><input ${dis} inputmode="numeric" type="number" min="0" max="100" step="1" data-set="${i}" data-key="lr" value="${esc(r.lr)}"></td><td><select ${dis} data-set="${i}" data-key="le"><option value="">–</option>${[5,6,7,8,9,10].map(v=>`<option value="${v}" ${String(r.le)===String(v)?'selected':''}>${v}</option>`).join('')}</select></td><td><input ${dis} type="checkbox" data-set="${i}" data-key="lc" ${r.lc?'checked':''}></td><td><input inputmode="decimal" type="number" min="0" max="500" step="0.5" data-set="${i}" data-key="mw" value="${esc(r.mw)}"></td><td><input inputmode="numeric" type="number" min="0" max="100" step="1" data-set="${i}" data-key="mr" value="${esc(r.mr)}"></td><td><select data-set="${i}" data-key="me"><option value="">–</option>${[5,6,7,8,9,10].map(v=>`<option value="${v}" ${String(r.me)===String(v)?'selected':''}>${v}</option>`).join('')}</select></td><td><input type="checkbox" data-set="${i}" data-key="mc" ${r.mc?'checked':''}></td></tr>`}).join('');
  $('#setRows').querySelectorAll('input,select').forEach(el=>el.addEventListener('change',()=>{const log=getLog(),row=log.sets[Number(el.dataset.set)];row[el.dataset.key]=el.type==='checkbox'?el.checked:el.value;log.updated=new Date().toISOString();recordHistory();saveState()}));
}
function recordHistory(){const k=`w${state.week}-${state.pass}`;const now=new Date().toISOString();state.history[k]={week:state.week,pass:state.pass,updated:now}}
function refreshProgress(){let done=0;for(const v of Object.values(state.logs))if(v.done)done++;const total=8*12;const pct=Math.min(100,Math.round(done/total*100));$('#sidebarWeek').textContent=`Vecka ${state.week} av 8`;$('#sidebarPercent').textContent=`${pct}%`;$('#sidebarProgress').style.width=`${Math.max(state.week/8*12.5,pct)}%`;$('#statWeek').textContent=`${state.week} / 8`;renderStatsIfVisible()}
function setPass(pass){state.pass=pass;state.exerciseIndex=0;saveState();renderToday();showView('today')}
function showView(view){$$('.view').forEach(v=>v.classList.remove('active-view'));$$('.nav-btn').forEach(b=>b.classList.remove('active'));const map={today:'#todayView',passA:'#todayView',passB:'#todayView',exercises:'#exercisesView',log:'#logView',stats:'#statsView',notes:'#notesView'};$(map[view]).classList.add('active-view');const btn=$(`.nav-btn[data-view="${view}"]`)||$('.nav-btn[data-view="today"]');btn.classList.add('active');if(view==='passA')setPass('A');if(view==='passB')setPass('B');if(view==='exercises')renderLibrary();if(view==='log')renderLogbook();if(view==='stats')renderStats();if(view==='notes'){$('#globalNotes').value=state.globalNotes||''}document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function renderLibrary(){const all=[...PROGRAM.A.exercises.map(x=>({...x,pass:'A'})),...PROGRAM.B.exercises.map(x=>({...x,pass:'B'}))];$('#exerciseLibrary').innerHTML=all.map(ex=>`<article class="library-card"><button data-pass="${ex.pass}" data-id="${ex.id}"><img src="${exerciseAsset(ex)}" alt="Illustration av ${esc(ex.name)}"><div class="library-card-content"><h3>${esc(ex.name)}</h3><p>${esc(ex.muscleLong)}</p><span class="pass-tag">Pass ${ex.pass}</span></div></button></article>`).join('');$('#exerciseLibrary').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.pass=b.dataset.pass;state.exerciseIndex=PROGRAM[state.pass].exercises.findIndex(x=>x.id===b.dataset.id);saveState();renderToday();showView('today')}))}
function activityForLog(log){return (log.sets||[]).some(r=>Object.values(r).some(v=>v!==''&&v!==false&&v!=null))||log.done||log.note}
function renderLogbook(){const entries=Object.entries(state.logs).filter(([,l])=>activityForLog(l)).sort((a,b)=>String(b[1].updated||'').localeCompare(String(a[1].updated||'')));const done=entries.filter(([,l])=>l.done).length;const sessions=new Set(entries.map(([k])=>k.split('-').slice(0,2).join('-'))).size;$('#logSummary').innerHTML=`<article class="summary-card"><small>Loggade övningar</small><strong>${entries.length}</strong></article><article class="summary-card"><small>Klara övningar</small><strong>${done}</strong></article><article class="summary-card"><small>Aktiva pass</small><strong>${sessions}</strong></article>`;$('#historyList').innerHTML=entries.length?entries.map(([k,l])=>{const m=k.match(/^w(\d+)-([AB])-(.+)$/);const ex=PROGRAM[m[2]].exercises.find(x=>x.id===m[3]);const lines=(l.sets||[]).map((r,i)=>{const L=r.lw||r.lr?`Lucas ${r.lw||'–'} kg × ${r.lr||'–'}`:'';const M=r.mw||r.mr?`Magnus ${r.mw||'–'} kg × ${r.mr||'–'}`:'';return [L,M].filter(Boolean).join(' · ')}).filter(Boolean);return `<article class="history-card"><div class="history-card-head"><div><h3>Vecka ${m[1]} · Pass ${m[2]} · ${esc(ex?.name||m[3])}</h3><small>${l.done?'✓ Klar':'Påbörjad'}${l.updated?` · ${new Date(l.updated).toLocaleDateString('sv-SE')}`:''}</small></div></div>${lines.length?`<p>${lines.map(esc).join('<br>')}</p>`:''}${l.note?`<p><b>Anteckning:</b> ${esc(l.note)}</p>`:''}</article>`}).join(''):'<article class="history-card"><h3>Ingen träning loggad ännu</h3><p>När ni fyller i ett set dyker det upp här automatiskt.</p></article>'}
function renderStats(){const entries=Object.entries(state.logs).filter(([,l])=>activityForLog(l));const done=entries.filter(([,l])=>l.done).length;const sessions=new Set(entries.map(([k])=>k.split('-').slice(0,2).join('-'))).size;$('#statExercises').textContent=done;$('#statSessions').textContent=sessions;$('#statWeek').textContent=`${state.week} / 8`;const counts=Array.from({length:8},(_,i)=>entries.filter(([k,l])=>k.startsWith(`w${i+1}-`)&&l.done).length);const max=Math.max(1,...counts);$('#weekChart').innerHTML=counts.map((v,i)=>`<div class="week-bar"><span>${v}</span><i style="height:${Math.max(4,v/max*170)}px"></i><b>V${i+1}</b></div>`).join('')}
function renderStatsIfVisible(){if($('#statsView').classList.contains('active-view'))renderStats()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='magnus-lucas-gymdata.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);showToast('Gymdata exporterad')}

$$('[data-pass]').forEach(b=>b.addEventListener('click',()=>setPass(b.dataset.pass)));
$('#weekSelect').addEventListener('change',e=>{state.week=Math.min(8,Math.max(1,Number(e.target.value)||1));saveState();renderToday()});
$('#completeExercise').addEventListener('click',()=>{const l=getLog();l.done=!l.done;l.updated=new Date().toISOString();recordHistory();saveState();renderToday();showToast(l.done?'Övningen markerad som klar':'Markeringen borttagen')});
$('#exerciseNotes').addEventListener('input',e=>{const l=getLog();l.note=e.target.value;l.updated=new Date().toISOString();recordHistory();saveState()});
$('#prevExercise').addEventListener('click',()=>{if(state.exerciseIndex>0){state.exerciseIndex--;saveState();renderToday();window.scrollTo({top:0,behavior:'smooth'})}});
$('#nextExercise').addEventListener('click',()=>{const n=PROGRAM[state.pass].exercises.length;state.exerciseIndex=state.exerciseIndex===n-1?0:state.exerciseIndex+1;saveState();renderToday();window.scrollTo({top:0,behavior:'smooth'})});
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#menuToggle').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$('#quickLog').addEventListener('click',()=>showView('log'));$('#exportData').addEventListener('click',exportData);
$('#globalNotes').addEventListener('input',e=>{state.globalNotes=e.target.value;saveState();$('#notesSaved').textContent='Sparat automatiskt.';clearTimeout(window.__noteTimer);window.__noteTimer=setTimeout(()=>$('#notesSaved').textContent='Sparas automatiskt på enheten.',1500)});
document.addEventListener('click',e=>{if(innerWidth<=760&&!e.target.closest('.sidebar')&&!e.target.closest('#menuToggle'))$('.sidebar').classList.remove('open')});

renderWeekOptions();renderToday();refreshProgress();$('#globalNotes').value=state.globalNotes||'';
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
